[build]
  # Directorio base del proyecto de Astro
  base = "nau-astro-site"
  
  # Comando de construcción a ejecutar desde la raíz del monorepo
  # Filtramos para construir solo el sitio de Astro
  command = "pnpm --filter nau-astro-site build"
  
  # Directorio de publicación, relativo a 'base'
  publish = "dist/"

[functions]
  directory = "netlify/functions"

[images]
  remote_images = ["^https://cdn\.sanity\.io/.*"]