[build]
  # Directorio base del proyecto de Astro
  base = "nau-astro-site"
  
  # Comando de construcción a ejecutar desde la raíz del monorepo
  # Filtramos para construir solo el sitio de Astro
  command = "pnpm --filter nau-astro-site build"
  
  # Directorio de publicación, relativo a la raíz del repositorio
  publish = "nau-astro-site/dist/"

[functions]
  directory = "nau-astro-site/netlify/functions"

[images]
  remote_images = ["^https://cdn\\.sanity\\.io/.*"]
