# Este archivo le da a Netlify las instrucciones de construcción.
# Tiene prioridad sobre cualquier configuración en la interfaz de Netlify.

[build]
  # Cambiamos el comando para usar npm, que es el estándar.
  command = "npm run build"
  # La carpeta que Netlify debe publicar después de la construcción.
  publish = "dist"