# Configuraci칩n para el sitio de Astro (Frontend)
[build]
  base = "nau-astro-site/"
  publish = "dist/"
  command = "pnpm install && pnpm run build"

# Permite que el CDN de im치genes de Netlify procese im치genes de tu CDN de Sanity.
[images]
  # Esta es una lista de expresiones regulares.
  # Este patr칩n permite cualquier imagen que provenga de https://cdn.sanity.io.
  remote_images = ["^https://cdn\.sanity\.io/.*"]
