# Este archivo le da a Netlify las instrucciones de construcción.
# Tiene prioridad sobre cualquier configuración en la interfaz de Netlify.

[build]
  command = "pnpm run build"
  # La carpeta que Netlify debe publicar después de la construcción.
  publish = "dist"

# Agregamos una variable de entorno para solucionar conflictos de dependencias.
[build.environment]
  NPM_FLAGS = "--legacy-peer-deps"

# Permite que el CDN de imágenes de Netlify procese imágenes de tu CDN de Sanity.
[images]
  # Esta es una lista de expresiones regulares.
  # Este patrón permite cualquier imagen que provenga de https://cdn.sanity.io.
  remote_images = ["^https://cdn\\.sanity\\.io/.*"]